<a href="https://colab.research.google.com/github/sudeeraattanayake/Machine-Learning/blob/main/SVR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#import lib

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#import datset

In [6]:
datset = pd.read_csv('Position_Salaries.csv')
X = datset.iloc[:, 1:-1].values
y = datset.iloc[:, -1].values

In [7]:
print(X)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [8]:
print(y)

[  45000   50000   60000   80000  110000  150000  200000  300000  500000
 1000000]


#feature scalining

In [9]:
y = y.reshape(len(y), 1)

In [11]:
print(y)


[[  45000]
 [  50000]
 [  60000]
 [  80000]
 [ 110000]
 [ 150000]
 [ 200000]
 [ 300000]
 [ 500000]
 [1000000]]


In [14]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()

In [15]:
X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y)

In [16]:
print(X)

[[-1.5666989 ]
 [-1.21854359]
 [-0.87038828]
 [-0.52223297]
 [-0.17407766]
 [ 0.17407766]
 [ 0.52223297]
 [ 0.87038828]
 [ 1.21854359]
 [ 1.5666989 ]]


In [17]:
print(y)

[[-0.72004253]
 [-0.70243757]
 [-0.66722767]
 [-0.59680786]
 [-0.49117815]
 [-0.35033854]
 [-0.17428902]
 [ 0.17781001]
 [ 0.88200808]
 [ 2.64250325]]


#train the model on the dataset

In [19]:
from sklearn.svm import SVR
regressor = SVR()
regressor.fit(X, y)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

#prediciting new result

In [24]:
prediction = regressor.predict(sc_X.transform([[6.5]]))
print(prediction)

[0.01150915]


In [26]:
prediction = sc_y.inverse_transform([[6.5]])
print(prediction)

[[6.5]]


#visulizing the SVR result